<?php

namespace Database\Seeders;

use App\Models\User as ModelsUser;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class User extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $user = [
            [
                'name' => 'Anggu Surya',
                'username' => 'anggu',
                'password' => bcrypt(123),
                'level' => 1,
                'kode_user' => bcrypt('admin'),
            ],
            [
                'name' => 'Siti Dahlia',
                'username' => 'lia',
                'password' => bcrypt(123),
                'level' => 2,
                'kode_user' => bcrypt('operator'),
            ],
            [
                'name' => 'Mira Hasmara',
                'username' => 'mira',
                'password' => bcrypt(123),
                'level' => 2,
                'kode_user' => bcrypt('operator'),
            ],
            [
                'name' => 'Ela Muliati',
                'username' => 'ela',
                'password' => bcrypt(123),
                'level' => 2,
                'kode_user' => bcrypt('operator'),
            ],
            [
                'name' => 'Nur Hasanah',
                'username' => 'sanah',
                'password' => bcrypt(123),
                'level' => 2,
                'kode_user' => bcrypt('operator'),
            ],
            [
                'name' => 'Desa Pulau Sejuk',
                'username' => 'pulausejuk',
                'password' => bcrypt(123),
                'level' => 3,
                'kode_user' => bcrypt('desa'),
            ],
            [
                'name' => 'Desa Sumber Makmur',
                'username' => 'sumbermakmur',
                'password' => bcrypt(123),
                'level' => 3,
                'kode_user' => bcrypt('desa'),
            ],
            [
                'name' => 'Desa Pematang Kuing',
                'username' => 'pematangkuing',
                'password' => bcrypt(123),
                'level' => 3,
                'kode_user' => bcrypt('desa'),
            ],
            [
                'name' => 'Desa Bulan-Bulan',
                'username' => 'desabulanbulan',
                'password' => bcrypt(123),
                'level' => 3,
                'kode_user' => bcrypt('desa'),
            ],
            [
                'name' => 'Desa Pematang Cengkering',
                'username' => 'desapematangcengkering',
                'password' => bcrypt(123),
                'level' => 3,
                'kode_user' => bcrypt('desa'),
            ],
            [
                'name' => 'Desa Tali Air Permai',
                'username' => 'desataliairpermai',
                'password' => bcrypt(123),
                'level' => 3,
                'kode_user' => bcrypt('desa'),
            ],
            [
                'name' => 'Desa Benteng',
                'username' => 'desabenteng',
                'password' => bcrypt(123),
                'level' => 3,
                'kode_user' => bcrypt('desa'),
            ],
            [
                'name' => 'Desa Bandar Rahmat',
                'username' => 'desabandarrahmat',
                'password' => bcrypt(123),
                'level' => 3,
                'kode_user' => bcrypt('desa'),
            ],
            [
                'name' => 'Perkebunan Petatal',
                'username' => 'ami',
                'password' => bcrypt(123),
                'level' => 3,
                'kode_user' => bcrypt('desa'),
            ],
            [
                'name' => 'Desa Tanjung Parapat',
                'username' => 'tanjungparapat',
                'password' => bcrypt(123),
                'level' => 3,
                'kode_user' => bcrypt('desa'),
            ],
            [
                'name' => 'Desa Perkebunan Sei balai',
                'username' => 'perkseibalai',
                'password' => bcrypt(123),
                'level' => 3,
                'kode_user' => bcrypt('desa'),
            ],
            [
                'name' => 'Desa Suka Ramai',
                'username' => 'sukaramai',
                'password' => bcrypt(123),
                'level' => 3,
                'kode_user' => bcrypt('desa'),
            ],
            [
                'name' => 'Desa Suka Ramai Sei Balai',
                'username' => 'desasukaramai',
                'password' => bcrypt(123),
                'level' => 3,
                'kode_user' => bcrypt('desa'),
            ],
            [
                'name' => 'Desa Sei Buah Keras',
                'username' => 'seibuahkeras',
                'password' => bcrypt(123),
                'level' => 3,
                'kode_user' => bcrypt('desa'),
            ],
            [
                'name' => 'Desa Pahlawan',
                'username' => 'desapahlawan',
                'password' => bcrypt(123),
                'level' => 3,
                'kode_user' => bcrypt('desa'),
            ],
            [
                'name' => 'Desa Brohol',
                'username' => 'desabrohol',
                'password' => bcrypt(123),
                'level' => 3,
                'kode_user' => bcrypt('desa'),
            ],
            [
                'name' => 'Desa Mangkai Baru',
                'username' => 'mangkaibaru',
                'password' => bcrypt(123),
                'level' => 3,
                'kode_user' => bcrypt('desa'),
            ],
            [
                'name' => 'Desa Lima Laras',
                'username' => 'limalaras',
                'password' => bcrypt(123),
                'level' => 3,
                'kode_user' => bcrypt('desa'),
            ],
            [
                'name' => 'Desa Karang Baru',
                'username' => 'karangbaru',
                'password' => bcrypt(123),
                'level' => 3,
                'kode_user' => bcrypt('desa'),
            ],
            [
                'name' => 'Desa Binjai Baru',
                'username' => 'binjaibaru',
                'password' => bcrypt(123),
                'level' => 3,
                'kode_user' => bcrypt('desa'),
            ],
            [
                'name' => 'Desa Bogak',
                'username' => 'desabogak',
                'password' => bcrypt(123),
                'level' => 3,
                'kode_user' => bcrypt('desa'),
            ],
            [
                'name' => 'Kelurahan Bagan Arya',
                'username' => 'baganarya',
                'password' => bcrypt(123),
                'level' => 3,
                'kode_user' => bcrypt('desa'),
            ],
            [
                'name' => 'Kelurahan Tanjung Tiram',
                'username' => 'tanjungtiram',
                'password' => bcrypt(123),
                'level' => 3,
                'kode_user' => bcrypt('desa'),
            ],
            [
                'name' => 'Desa Suka Jaya',
                'username' => 'desasukajaya',
                'password' => bcrypt(123),
                'level' => 3,
                'kode_user' => bcrypt('desa'),
            ],
            [
                'name' => 'Desa Pahang',
                'username' => 'desapahang',
                'password' => bcrypt(123),
                'level' => 3,
                'kode_user' => bcrypt('desa'),
            ],
            [
                'name' => 'Perkebunan Sei Bejangkar',
                'username' => 'perkseibejangkar',
                'password' => bcrypt(123),
                'level' => 3,
                'kode_user' => bcrypt('desa'),
            ],
            [
                'name' => 'Desa Ujung Kubu',
                'username' => 'desaujungkubu',
                'password' => bcrypt(123),
                'level' => 3,
                'kode_user' => bcrypt('desa'),
            ],
            [
                'name' => 'Desa Guntung',
                'username' => 'desaguntung',
                'password' => bcrypt(123),
                'level' => 3,
                'kode_user' => bcrypt('desa'),
            ],
            [
                'name' => 'Desa Bandar Sono',
                'username' => 'desabandarsono',
                'password' => bcrypt(123),
                'level' => 3,
                'kode_user' => bcrypt('desa'),
            ],
            [
                'name' => 'Desa Mekar Laras',
                'username' => 'desamekarlaras',
                'password' => bcrypt(123),
                'level' => 3,
                'kode_user' => bcrypt('desa'),
            ],
            [
                'name' => 'Desa Pematang Panjang',
                'username' => 'desapematangpanjang',
                'password' => bcrypt(123),
                'level' => 3,
                'kode_user' => bcrypt('desa'),
            ],
            [
                'name' => 'Desa Kuala Tanjung',
                'username' => 'desakualatanjung',
                'password' => bcrypt(123),
                'level' => 3,
                'kode_user' => bcrypt('desa'),
            ],
            [
                'name' => 'Desa Pakam Raya Selatan',
                'username' => 'pakamrayaselatan',
                'password' => bcrypt(123),
                'level' => 3,
                'kode_user' => bcrypt('desa'),
            ],
            [
                'name' => 'Desa Sei Mentaram',
                'username' => 'seimentaram',
                'password' => bcrypt(123),
                'level' => 3,
                'kode_user' => bcrypt('desa'),
            ],
            [
                'name' => 'Desa Sentang',
                'username' => 'desasentang',
                'password' => bcrypt(123),
                'level' => 3,
                'kode_user' => bcrypt('desa'),
            ],
            [
                'name' => 'Desa Medang',
                'username' => 'desamedang',
                'password' => bcrypt(123),
                'level' => 3,
                'kode_user' => bcrypt('desa'),
            ],
            [
                'name' => 'Desa Tanjung Mulia',
                'username' => 'tanjungmulia',
                'password' => bcrypt(123),
                'level' => 3,
                'kode_user' => bcrypt('desa'),
            ],
            [
                'name' => 'Desa Jati Mulia',
                'username' => 'jatimulia',
                'password' => bcrypt(123),
                'level' => 3,
                'kode_user' => bcrypt('desa'),
            ],
            [
                'name' => 'Desa Empat Negeri',
                'username' => 'desa4negeri',
                'password' => bcrypt(123),
                'level' => 3,
                'kode_user' => bcrypt('desa'),
            ],
            [
                'name' => 'Desa Kwala Gunung',
                'username' => 'kwalagunung',
                'password' => bcrypt(123),
                'level' => 3,
                'kode_user' => bcrypt('desa'),
            ],
            [
                'name' => 'Desa Cahaya Pardomuan',
                'username' => 'cahayapardomuan',
                'password' => bcrypt(123),
                'level' => 3,
                'kode_user' => bcrypt('desa'),
            ],
            [
                'name' => 'Desa Sumber Rejo',
                'username' => 'sumberrejo',
                'password' => bcrypt(123),
                'level' => 3,
                'kode_user' => bcrypt('desa'),
            ],
            [
                'name' => 'Desa Sumber Tani',
                'username' => 'desasumbertani',
                'password' => bcrypt(123),
                'level' => 3,
                'kode_user' => bcrypt('desa'),
            ],
            [
                'name' => 'Desa Indra Yaman',
                'username' => 'desaindrayaman',
                'password' => bcrypt(123),
                'level' => 3,
                'kode_user' => bcrypt('desa'),
            ],
            [
                'name' => 'Desa Suko Rejo',
                'username' => 'desasukorejo',
                'password' => bcrypt(123),
                'level' => 3,
                'kode_user' => bcrypt('desa'),
            ],
            [
                'name' => 'Desa Panjang',
                'username' => 'desapanjang',
                'password' => bcrypt(123),
                'level' => 3,
                'kode_user' => bcrypt('desa'),
            ],
            [
                'name' => 'Desa Sei Raja',
                'username' => 'seiraja',
                'password' => bcrypt(123),
                'level' => 3,
                'kode_user' => bcrypt('desa'),
            ],
        ];

        foreach ($user as $key => $value) {
            ModelsUser::create($value);
        }
    }
}